/** WhatsApp-supported language codes (language name → code). */
export const LANGUAGE_CODES: { language: string; code: string }[] = [
  { language: 'Afrikaans', code: 'af' },
  { language: 'Albanian', code: 'sq' },
  { language: 'Arabic', code: 'ar' },
  { language: 'Arabic (EGY)', code: 'ar_EG' },
  { language: 'Arabic (UAE)', code: 'ar_AE' },
  { language: 'Arabic (LBN)', code: 'ar_LB' },
  { language: 'Arabic (MAR)', code: 'ar_MA' },
  { language: 'Arabic (QAT)', code: 'ar_QA' },
  { language: 'Azerbaijani', code: 'az' },
  { language: 'Belarusian', code: 'be_BY' },
  { language: 'Bengali', code: 'bn' },
  { language: 'Bengali (IND)', code: 'bn_IN' },
  { language: 'Bulgarian', code: 'bg' },
  { language: 'Catalan', code: 'ca' },
  { language: 'Chinese (CHN)', code: 'zh_CN' },
  { language: 'Chinese (HKG)', code: 'zh_HK' },
  { language: 'Chinese (TAI)', code: 'zh_TW' },
  { language: 'Croatian', code: 'hr' },
  { language: 'Czech', code: 'cs' },
  { language: 'Danish', code: 'da' },
  { language: 'Dari', code: 'prs_AF' },
  { language: 'Dutch', code: 'nl' },
  { language: 'Dutch (BEL)', code: 'nl_BE' },
  { language: 'English', code: 'en' },
  { language: 'English (UK)', code: 'en_GB' },
  { language: 'English (US)', code: 'en_US' },
  { language: 'English (UAE)', code: 'en_AE' },
  { language: 'English (AUS)', code: 'en_AU' },
  { language: 'English (CAN)', code: 'en_CA' },
  { language: 'English (GHA)', code: 'en_GH' },
  { language: 'English (IRL)', code: 'en_IE' },
  { language: 'English (IND)', code: 'en_IN' },
  { language: 'English (JAM)', code: 'en_JM' },
  { language: 'English (MYS)', code: 'en_MY' },
  { language: 'English (NZL)', code: 'en_NZ' },
  { language: 'English (QAT)', code: 'en_QA' },
  { language: 'English (SGP)', code: 'en_SG' },
  { language: 'English (UGA)', code: 'en_UG' },
  { language: 'English (ZAF)', code: 'en_ZA' },
  { language: 'Estonian', code: 'et' },
  { language: 'Filipino', code: 'fil' },
  { language: 'Finnish', code: 'fi' },
  { language: 'French', code: 'fr' },
  { language: 'French (BEL)', code: 'fr_BE' },
  { language: 'French (CAN)', code: 'fr_CA' },
  { language: 'French (CHE)', code: 'fr_CH' },
  { language: 'French (CIV)', code: 'fr_CI' },
  { language: 'French (MAR)', code: 'fr_MA' },
  { language: 'Georgian', code: 'ka' },
  { language: 'German', code: 'de' },
  { language: 'German (AUT)', code: 'de_AT' },
  { language: 'German (CHE)', code: 'de_CH' },
  { language: 'Greek', code: 'el' },
  { language: 'Gujarati', code: 'gu' },
  { language: 'Hausa', code: 'ha' },
  { language: 'Hebrew', code: 'he' },
  { language: 'Hindi', code: 'hi' },
  { language: 'Hungarian', code: 'hu' },
  { language: 'Indonesian', code: 'id' },
  { language: 'Irish', code: 'ga' },
  { language: 'Italian', code: 'it' },
  { language: 'Japanese', code: 'ja' },
  { language: 'Kannada', code: 'kn' },
  { language: 'Kazakh', code: 'kk' },
  { language: 'Kinyarwanda', code: 'rw_RW' },
  { language: 'Korean', code: 'ko' },
  { language: 'Kyrgyz (Kyrgyzstan)', code: 'ky_KG' },
  { language: 'Lao', code: 'lo' },
  { language: 'Latvian', code: 'lv' },
  { language: 'Lithuanian', code: 'lt' },
  { language: 'Macedonian', code: 'mk' },
  { language: 'Malay', code: 'ms' },
  { language: 'Malayalam', code: 'ml' },
  { language: 'Marathi', code: 'mr' },
  { language: 'Norwegian', code: 'nb' },
  { language: 'Pashto', code: 'ps_AF' },
  { language: 'Persian', code: 'fa' },
  { language: 'Polish', code: 'pl' },
  { language: 'Portuguese (BR)', code: 'pt_BR' },
  { language: 'Portuguese (POR)', code: 'pt_PT' },
  { language: 'Punjabi', code: 'pa' },
  { language: 'Romanian', code: 'ro' },
  { language: 'Russian', code: 'ru' },
  { language: 'Serbian', code: 'sr' },
  { language: 'Sinhala', code: 'si_LK' },
  { language: 'Slovak', code: 'sk' },
  { language: 'Slovenian', code: 'sl' },
  { language: 'Spanish', code: 'es' },
  { language: 'Spanish (ARG)', code: 'es_AR' },
  { language: 'Spanish (CHL)', code: 'es_CL' },
  { language: 'Spanish (COL)', code: 'es_CO' },
  { language: 'Spanish (CRI)', code: 'es_CR' },
  { language: 'Spanish (DOM)', code: 'es_DO' },
  { language: 'Spanish (ECU)', code: 'es_EC' },
  { language: 'Spanish (HND)', code: 'es_HN' },
  { language: 'Spanish (MEX)', code: 'es_MX' },
  { language: 'Spanish (PAN)', code: 'es_PA' },
  { language: 'Spanish (PER)', code: 'es_PE' },
  { language: 'Spanish (SPA)', code: 'es_ES' },
  { language: 'Spanish (URY)', code: 'es_UY' },
  { language: 'Swahili', code: 'sw' },
  { language: 'Swedish', code: 'sv' },
  { language: 'Tamil', code: 'ta' },
  { language: 'Telugu', code: 'te' },
  { language: 'Thai', code: 'th' },
  { language: 'Turkish', code: 'tr' },
  { language: 'Ukrainian', code: 'uk' },
  { language: 'Urdu', code: 'ur' },
  { language: 'Uzbek', code: 'uz' },
  { language: 'Vietnamese', code: 'vi' },
  { language: 'Zulu', code: 'zu' },
];
